[project]
name = "distributed-llm-inference"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "langchain>=1.1.0",
    "langchain-ollama>=1.0.0",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
